icon: https://www.buzzing.cc/icon.png
favicon: https://www.buzzing.cc/favicon.ico
root_domain: buzzing.cc
page_size: 200
translated_items_per_page: 100
max_files_per_site: -1
dev:
  max_files_per_site: 4
  translated_items_per_page: 2
languages:
  [
    { code: "zh-Hans", name: "ç®€ä½“ä¸­æ–‡", prefix: "" },
    { code: "zh-Hant", name: "ç¹ä½“ä¸­æ–‡", prefix: "zh-Hant/" },
    { code: "en", name: "English", prefix: "en/" },
    { code: "ja", name: "æ—¥æœ¬èªž", prefix: "ja/" },
  ]
translations:
  zh-Hans:
    about_label: å…³äºŽ
    subscription_label: è®¢é˜…åœ°å€
    powered_by_label: èƒŒåŽçš„äººâ¤ï¸
    languages_label: è¯¥é¡µé¢å…¶ä»–è¯­è¨€
    more_sites_label: å§Šå¦¹ç«™ç‚¹
    tags_label: æ‰€æœ‰æ ‡ç­¾
    archive_label: åŽ†å²å½’æ¡£
    issues_label: å¾€æœŸç²¾é€‰
    more_label: æ›´å¤š
    less_label: æ”¶èµ·
    more_post_label: å¥½å§, å¦‚æžœä½ è¿˜æ²¡çœ‹å¤Ÿ... ä»¥ä¸‹ðŸ‘‡
  en:
    about_label: About
    subscription_label: Subscription
    powered_by_label: Made by â¤ï¸
    languages_label: Other languages
    more_sites_label: More feeds
    tags_label: All tags
    archive_label: Archive
    issues_label: Past issues
    more_label: More
    less_label: Less
  ja:
    about_label: ã“ã®ãƒšãƒ¼ã‚¸ã«ã¤ã„ã¦
    subscription_label: è³¼èª­
    powered_by_label: è£½ä½œè€… â¤ï¸
    languages_label: ä»–ã®è¨€èªž
    more_sites_label: ä»–ã®ãƒ•ã‚£ãƒ¼ãƒ‰
    tags_label: ã™ã¹ã¦ã®ã‚¿ã‚°
    archive_label: ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–
    issues_label: éŽåŽ»ã®å•é¡Œ
    more_label: ã‚‚ã£ã¨
    less_label: é–‰ã˜ã‚‹
archive:
  port: 9000
  siteIdentifier: i
  tags: []

sites:
  devfeed:
    redirect: true
    port: 8000
    dev: true
    tags:
      - source-hackernews-index
    archive: false
    translations:
      "zh-Hans":
        title: "Reddit çƒ­é—¨"
        short_title: "Reddit çƒ­é—¨"
        description: "ç”¨ä¸­æ–‡æµè§ˆRedditçƒ­é—¨å†…å®¹"

  hackernews:
    port: 8001
    tags:
      - hn
      - source-hackernews-index
    translations:
      "zh-Hans":
        title: "Hacker News é¦–é¡µ"
        short_title: "HNé¦–é¡µ"
        description: "ç”¨ä¸­æ–‡æµè§ˆHacker News é¦–é¡µæœ€æ–°æ–‡ç« "
        keywords: "HackerNews å¤´æ¡, Hacker News ä¸­æ–‡, Hacker News Story"
      "en":
        title: "Hacker News Front Page"
        short_title: "HN Front Page"
        description: "Hacker News Front Page Feed"
        keywords: "HackerNews å¤´æ¡, Hacker News ä¸­æ–‡, Hacker News Story"

  hn:
    port: 8002
    domain: prodhn.buzzing.cc
    redirect: true
    tags:
      - hn
      - source-hackernews-best
    translations:
      "zh-Hans":
        title: "Hacker News çƒ­é—¨"
        short_title: "HNçƒ­é—¨"
        description: "è¿½è¸ªHacker Newsä¸Šè¶…è¿‡ 200 pointsçš„å¸–å­"

  askhn:
    port: 8003
    domain: prodaskhn.buzzing.cc
    tags:
      - hn
      - source-hackernews-ask
    translations:
      "zh-Hans":
        title: "Hacker News é—®ç­”"
        short_title: "HNé—®ç­”"
        description: "è¿½è¸ª Hacker News ä¸Šçš„é—®ç­”"

  showhn:
    port: 8004
    tags:
      - hn
      - source-hackernews-show
    translations:
      "zh-Hans":
        title: "Show HN"
        short_title: "Show HN"
        description: "è¿½è¸ª Hacker News ä¸Šçš„é¡¹ç›®å±•ç¤º"

  reddit:
    port: 8005
    redirect: true
    tags:
      - reddit
      - source-reddit-top
    translations:
      "zh-Hans":
        title: "Reddit çƒ­é—¨"
        short_title: "Reddit çƒ­é—¨"
        description: "ç”¨ä¸­æ–‡æµè§ˆRedditçƒ­é—¨å†…å®¹"
      "en":
        title: "Buzzing on Reddit"
        description: "See what's buzzing on Reddit in your native language"
        keywords: "Reddit Hot, Reddit Hot Feed"

  ask:
    port: 8007
    redirect: true
    tags:
      - reddit
      - source-reddit-ask
    translations:
      "zh-Hans":
        title: "Reddit çƒ­é—¨æé—®"
        short_title: "Redditæé—®"
        description: "ç”¨ä¸­æ–‡æµè§ˆ Reddit ä¸Šçš„çƒ­é—¨æé—®"

  stocks:
    port: 8008
    redirect: true
    tags:
      - reddit
      - finance
      - source-reddit-stocks
      - source-twitter-stocks
      # - source-reddit-wallstreetbets
      # - source-reddit-bogleheads
    translations:
      "zh-Hans":
        title: "å›½å¤–è‚¡å¸‚çƒ­é—¨"
        description: "ç”¨ä¸­æ–‡æµè§ˆå›½å¤–è‚¡ç¥¨ç¤¾åŒºé‡Œçš„çƒ­é—¨è®¨è®º"
  news:
    port: 8006
    archive: true
    redirect: true
    tags:
      - news
      - source-google-news
    translations:
      "zh-Hans":
        title: "å›½å¤–æ–°é—»å¤´æ¡ - å…¨çƒæ–°é—»å¤´æ¡ - ç¾Žå›½æ–°é—»å¤´æ¡"
        short_title: "å›½å¤–æ–°é—»"
        description: "ç”¨ä¸­æ–‡æµè§ˆå›½å¤–æ–°é—»å¤´æ¡ï¼Œç¾Žå›½æ–°é—»å¤´æ¡ï¼Œå…¨çƒæ–°é—»(è¥¿æ–¹åª’ä½“)å¤´æ¡"
      "en":
        title: "Buzzing on World News"
        description: "See what's buzzing on the news in your native language"
        keywords: "Buzzing News, Buzzing News Feed"
  ph:
    port: 8009
    archive: true
    redirect: true
    tags:
      - tech
      - source-producthunt-top
    translations:
      "zh-Hans":
        title: "Product Hunt"
        short_title: "å›½å¤–æ–°é—»"
        description: "ç”¨ä¸­æ–‡æµè§ˆå›½å¤–æ–°é—»å¤´æ¡ï¼Œç¾Žå›½æ–°é—»å¤´æ¡ï¼Œå…¨çƒæ–°é—»(è¥¿æ–¹åª’ä½“)å¤´æ¡"
      "en":
        title: "Buzzing on World News"
        description: "See what's buzzing on the news in your native language"
        keywords: "Buzzing News, Buzzing News Feed"
  crypto:
    port: 8010
    archive: true
    redirect: true
    tags:
      - tech
      - source-crypto-reddit
      - source-crypto-twitter
    translations:
      "zh-Hans":
        title: "åŠ å¯†è´§å¸çƒ­é—¨è®¨è®º"
        short_title: "åŠ å¯†è´§å¸"
        description: "åŠ å¯†è´§å¸çƒ­é—¨è®¨è®º"
  dev:
    port: 8011
    archive: true
    redirect: true
    tags:
      - tech
      - source-devto
    translations:
      "zh-Hans":
        title: "å¼€å‘è€…çƒ­é—¨è®¨è®º"
        short_title: "å¼€å‘è€…"
        description: "å¼€å‘è€…çƒ­é—¨è®¨è®º"
  quora:
    port: 8012
    archive: true
    redirect: true
    tags:
      - ask
      - source-quora
    translations:
      "zh-Hans":
        title: "Quora çƒ­é—¨é—®ç­”"
        short_title: "Quoraçƒ­é—¨"
        description: "Quora çƒ­é—¨é—®ç­”"
  depth:
    port: 8013
    archive: true
    redirect: true
    tags:
      - depth
      - source-reddit-depth
    translations:
      "zh-Hans":
        title: "æ·±åº¦æ–‡ç« åˆ†äº«"
        short_title: "æ·±åº¦æ€è€ƒ"
        description: "Reddit ç²¾ç¥žé£Ÿç²®å°ç»„"
  nytimes:
    port: 8014
    archive: true
    redirect: true
    tags:
      - depth
      - news
      - source-twitter-nytimes
    translations:
      "zh-Hans":
        title: "çº½çº¦æ—¶æŠ¥çƒ­é—¨æ–‡ç« "
        short_title: "çº½çº¦æ—¶æŠ¥"
        description: "çº½çº¦æ—¶æŠ¥çƒ­é—¨æ–‡ç« "
  wsj:
    port: 8015
    archive: true
    redirect: true
    tags:
      - depth
      - news
      - source-twitter-wsj
    translations:
      "zh-Hans":
        title: "åŽå°”è¡—æ—¥æŠ¥çƒ­é—¨æ–‡ç« "
        short_title: "åŽå°”è¡—æ—¥æŠ¥"
        description: "åŽå°”è¡—æ—¥æŠ¥çƒ­é—¨æ–‡ç« "
  economist:
    port: 8016
    archive: true
    redirect: true
    tags:
      - depth
      - news
      - source-twitter-economist
    translations:
      "zh-Hans":
        title: "ç»æµŽå­¦äººçƒ­é—¨æ–‡ç« "
        short_title: "ç»æµŽå­¦äºº"
        description: "ç»æµŽå­¦äººçƒ­é—¨æ–‡ç« "
  sideproject:
    port: 8017
    archive: true
    redirect: true
    tags:
      - sideproject
      - source-reddit-sideproject
    translations:
      "zh-Hans":
        title: "ä¸šä½™é¡¹ç›®åˆ†äº«äº¤æµ"
        short_title: "ä¸šä½™é¡¹ç›®"
        description: "Reddit ä¸šä½™é¡¹ç›®å°ç»„"
sources:
  - url: https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en
    type: googlenews
    id: source-google-news
    rules:
      - type: limit
        value: "2"
  - url: https://hn.algolia.com/api/v1/search_by_date?tags=front_page&hitsPerPage=50
    type: hn
    id: source-hackernews-index
  - url: http://hn.algolia.com/api/v1/search_by_date?tags=(story,poll,show_hn,ask_hn)&numericFilters=points>=200&hitsPerPage=50
    type: hn
    id: source-hackernews-best
  - url: https://hn.algolia.com/api/v1/search_by_date?tags=(ask_hn)&hitsPerPage=50
    type: hn
    id: source-hackernews-ask
  - url: https://hn.algolia.com/api/v1/search_by_date?tags=(show_hn)&hitsPerPage=50
    type: hn
    id: source-hackernews-show
  - url: https://www.reddit.com/r/all/top/.json?raw_json=1
    type: reddit
    id: source-reddit-top
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "85000"
  - url: https://www.reddit.com/r/AskReddit/top/.json?raw_json=1
    type: reddit
    id: source-reddit-ask
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "70000"
  - url:
      - https://www.reddit.com/r/TooAfraidToAsk/top/.json?raw_json=1
      - https://www.reddit.com/r/NoStupidQuestions/top/.json?raw_json=1
    type: reddit
    id: source-reddit-ask
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "45000"
  - url:
      - https://www.reddit.com/r/Ask_Politics/top/.json?raw_json=1
      - https://www.reddit.com/r/AskHistorians/top/.json?raw_json=1
      - https://www.reddit.com/r/AskWomen/top/.json?raw_json=1
      - https://www.reddit.com/r/TrueAskReddit/top/.json?raw_json=1
      - https://www.reddit.com/r/askscience/top/.json?raw_json=1
      - https://www.reddit.com/r/askphilosophy/top/.json?raw_json=1
    id: source-reddit-ask
    type: reddit
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "300"

  - url: https://www.reddit.com/r/wallstreetbets/top/.json?raw_json=1
    type: reddit
    id: source-reddit-wallstreetbets
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "4000"
  - url: https://www.reddit.com/r/Bogleheads/top/.json?raw_json=1
    type: reddit
    id: source-reddit-bogleheads
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "15"
  - url:
      - https://www.reddit.com/r/stocks/top/.json?raw_json=1
      - https://www.reddit.com/r/investing/top/.json?raw_json=1
    type: reddit
    id: source-reddit-stocks
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "40"
  - id: source-producthunt-top
    url: https://api.producthunt.com/v2/api/graphql
    type: ph
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "60"
  - id: source-crypto-reddit
    url:
      - https://www.reddit.com/r/CryptoCurrency/top/.json?raw_json=1
      - https://www.reddit.com/r/Bitcoin/top/.json?raw_json=1
    type: reddit
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "400"

  - url: https://dev.to/api/articles?top=3
    id: source-devto
    type: devto
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "40"

  - url: https://www.reddit.com/r/SideProject/top/.json?raw_json=1
    id: source-reddit-sideproject
    type: reddit
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "4"
  - url:
      - https://www.reddit.com/r/TrueReddit/top/.json?raw_json=1
      - https://www.reddit.com/r/Foodforthought/top/.json?raw_json=1
    id: source-reddit-depth
    type: reddit
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "50"
  - url: nytimes
    params:
      include_rts: false
    id: source-twitter-nytimes
    type: twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "1000"
  - url: wsj
    params:
      include_rts: false
    id: source-twitter-wsj
    type: twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "150"
  - url: TheEconomist
    params:
      include_rts: false
    id: source-twitter-economist
    type: twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "150"
  - url:
      - charliebilello
      - Stocktwits
      - MarketWatch
      - The_Real_Fly
      - awealthofcs
      - michaelbatnick
      - InvestmentTalkk
    type: twitter
    id: source-twitter-stocks
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "400"
  - url:
      - s2fmultiple
    type: twitter
    id: source-crypto-twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "200"
  - url:
      - 100trillionUSD
    type: twitter
    id: source-crypto-twitter
    rules:
      - type: greaterEqual
        key: getWeightedScore
        value: "3000"
  - url: Quora
    params:
      include_rts: false
    id: source-quora
    type: twitter
    rules:
      - type: include
        key: getTitle
        value: "?"
